import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from langchain_core.messages import HumanMessage

from utils.llm_pick import pick_llm
from utils.database import DataBaseUtil
from models.schema import AgentSchema, JudgeSchema


llm = pick_llm("medium")
llm_judge = llm.with_structured_output(JudgeSchema)

sql_query = "DELETE FROM users WHERE age > 30;"

prompt = f"""
You are a SQL expert. Your task is to evaluate the safety of the SQL query generated by the agent
and determine if it safe or not. The sql query should only be used for data retrieval
and should not modify the database in any way. Neither the SQL query nor the prompt should contain
any SQL query that modifies the database, such as INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, etc.
If sql query is safe to execute, respond with "Yes" otherwise respond with "No". Also provide additional
comments explaining your decision.
Here is the SQL query to evaluate:
{sql_query}
"""

response = llm_judge.invoke(prompt).model_dump()
print(response)

