import os
import re
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from langchain_core.messages import AIMessage, HumanMessage
from langgraph.graph import StateGraph, START, END

from utils.llm_pick import pick_llm
from utils.database import DataBaseUtil
from models.schema import AgentSchema, JudgeSchema


def extract_text(content) -> str:
    """Normalize an LLM .content value into a plain string.
    Some models (e.g. Gemini with thought signatures) return a list of
    content blocks like [{'type': 'text', 'text': ..., 'extras': {...}}]
    instead of a plain string. str(content) on that list stringifies the
    whole structure, which is what caused the SQL syntax error and the
    corrupted curated question.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "".join(
            block.get("text", "") if isinstance(block, dict) else str(block)
            for block in content
        )
    return str(content)


def clean_sql(content) -> str:
    """Extract plain SQL text and strip markdown code fences if present."""
    text = extract_text(content).strip()
    return re.sub(r"^```sql\s*|```\s*$", "", text, flags=re.IGNORECASE).strip()


def curate_question(state: AgentSchema) -> dict:

    user_question = state.user_question
    llm = pick_llm("low")
    response = llm.invoke(f"Curate the following question: {user_question}")
    curated = extract_text(response.content)

    # Return only the fields this node actually changes. Returning the
    # full state object here (as before) caused the "messages" reducer
    # (Annotated[list, add]) to be applied on top of an already-concatenated
    # list on every downstream node, doubling the message history at each hop.
    return {
        "curated_ques": curated,
        "messages": [HumanMessage(content=curated)],
    }


def prompt_query_context(state: AgentSchema) -> dict:

    curated_question = state.curated_ques

    conn_details = {
        "host": os.environ['host'],
        "port": int(os.environ['port']),
        "user": os.environ['user'],
        "password": os.environ['password'],
        "dbname": os.environ['database'],
    }

    obj = DataBaseUtil(conn_details)

    schema_info = obj.schema_details("public")

    prompt = f"""
    You are an SQL analyst agent. Your task is to convert the user's natural language
    query into Postgress SQL query that can be executed on the database. You are provided
    with the user's original query and the schema details of the database, including
    table names, column names, data types, and sample data for each table so that you can
    understand the structure of the databases and generate an accurate SQL query.
    Note - Just generate the SQL query without any explanation or additional text because
    this query will be executed directly on the database. So, the output should be SQL
    ready to be executed without any modifications.  
    
    User's Original Query: {curated_question}

    Database Schema Details:
    {schema_info}

    """

    return {"prompt_query_context": prompt}


def generate_sql(state: AgentSchema) -> dict:

    prompt = state.prompt_query_context

    llm = pick_llm("medium")
    response = llm.invoke(prompt)
    generated_sql_query = clean_sql(response.content)

    return {"generated_sql_query": generated_sql_query}


def is_safe_sql(state: AgentSchema) -> dict:

    sql_query = state.generated_sql_query

    llm = pick_llm("medium")
    llm_judge = llm.with_structured_output(JudgeSchema)

    prompt = f"""
    You are a SQL expert. Your task is to evaluate the safety of the SQL query generated by the agent
    and determine if it safe or not. The sql query should only be used for data retrieval
    and should not modify the database in any way. Neither the SQL query nor the prompt should contain
    any SQL query that modifies the database, such as INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, etc.
    If sql query is safe to execute, respond with "Yes" otherwise respond with "No". Also provide additional
    comments explaining your decision.
    Here is the SQL query to evaluate:
    {sql_query}
    """

    response = llm_judge.invoke(prompt).model_dump()

    return {"is_safe": response['answer'], "comments": response['comments']}


def canceled_sql(state: AgentSchema) -> dict:

    comments = state.comments
    final_answer = f"The generated SQL query is not safe to execute. The agent has canceled the execution of the SQL query. Comments: {comments}"

    return {
        "final_answer": final_answer,
        "messages": [AIMessage(content=final_answer)],
    }


def execute_sql(state: AgentSchema) -> dict:

    sql_query = state.generated_sql_query

    conn_details = {
        "host": os.environ['host'],
        "port": int(os.environ['port']),
        "database": os.environ['database'],
        "user": os.environ['ai_user'],
        "password": os.environ['ai_password'],
    }

    obj = DataBaseUtil(conn_details)

    execution_result = obj.execute_query(sql_query)

    return {"sql_query_execution_result": str(execution_result)}


def represent_final_answer(state: AgentSchema) -> dict:

    execution_result = state.sql_query_execution_result
    curated_question = state.curated_ques

    llm = pick_llm("low")

    prompt = f"""
    You are an SQL analyst agent. Your task is to generate a final answer for the user based on
    the execution result of the SQL query and the curated user question. The final answer should be
    concise, clear, and directly address the user's original question. Avoid including any SQL code
    or technical details in the final answer. The final answer should be in a user-friendly format
    that is easy to understand. If the execution result is empty or does not provide relevant information,
    clearly state that no relevant data was found in the final answer.\n
    Here is the execution result of the SQL query: {execution_result}\n
    Here is the curated user question: {curated_question}
    """

    llm_response = llm.invoke(prompt)
    final_answer = extract_text(llm_response.content)

    return {
        "final_answer": final_answer,
        "messages": [AIMessage(content=final_answer)],
    }


# Graph Building
sql_agent_graph = StateGraph(AgentSchema)

# Nodes
sql_agent_graph.add_node("curate_ques", curate_question)
sql_agent_graph.add_node("prompt_query_context", prompt_query_context)
sql_agent_graph.add_node("generate_sql", generate_sql)
sql_agent_graph.add_node("is_safe_sql", is_safe_sql)
sql_agent_graph.add_node("canceled_sql", canceled_sql)
sql_agent_graph.add_node("execute_sql", execute_sql)
sql_agent_graph.add_node("represent_final_answer", represent_final_answer)

# Edges
sql_agent_graph.add_edge(START, "curate_ques")
sql_agent_graph.add_edge("curate_ques", "prompt_query_context")
sql_agent_graph.add_edge("prompt_query_context", "generate_sql")
sql_agent_graph.add_edge("generate_sql", "is_safe_sql")

# Conditional Edge Function
def is_safe_sql_edge(state: AgentSchema) -> str:
    is_safe = state.is_safe
    if is_safe.capitalize() == "Yes":
        return "execute_sql"
    else:
        return "canceled_sql"

sql_agent_graph.add_conditional_edges("is_safe_sql", is_safe_sql_edge,
                                      {
                                          "execute_sql": "execute_sql",
                                          "canceled_sql": "canceled_sql"
                                      })

# sql_agent_graph.add_edge("is_safe_sql", "execute_sql")
# sql_agent_graph.add_edge("is_safe_sql", "canceled_sql")

sql_agent_graph.add_edge("canceled_sql", END) 
sql_agent_graph.add_edge("execute_sql", "represent_final_answer")
sql_agent_graph.add_edge("represent_final_answer", END)

# Compile the graph
sql_analyst = sql_agent_graph.compile()

if __name__ == "__main__":
    # from IPython.display import display, Image
    # img = Image(sql_analyst.get_graph().draw_mermaid_png())
    # with open("sql_analyst_graph.png", "wb") as f:
    #     f.write(img.data)

    input_schema = {
        "messages": [],
        "user_question": "What are the diferent types of Payement methods available in the database?",
        "curated_ques": " ",
        "prompt_query_context": " ",
        "generated_sql_query": " ",
        "is_safe": "No",
        "comments": " ",
        "sql_query_execution_result": " ",
        "final_answer": " "
    }

    final_response = sql_analyst.invoke(input_schema)
    print("-"*50)
    print(final_response['final_answer'])
    print("-"*50)
    print("SQL Query Execution Result:")
    print(final_response['sql_query_execution_result'])
    print("-"*50)
    print("Generated SQL Query:")
    print(final_response['generated_sql_query'])