from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages to be processed by the agent")
    user_question: str = Field(..., description="The original question asked by the user")
    curated_ques: str = Field(..., description="Curated user question")
    prompt_query_context: str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query: str = Field(..., description="The SQL query generated by the agent based on curated question and prompt context")
    is_safe: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL is safe to execute or not")
    comments: str = Field(..., description="Comments regarding the safety of the generated SQL query")
    sql_query_execution_result: str = Field(..., description="The result of executing the generated SQL query on the database")
    final_answer: str = Field(..., description="The final answer generated by the agent based on the sql query execution result and curated question")

class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(..., description="Additional comments or feedback regarding the safety of the generated SQL query")

class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages to be processed by the ETL agent")

class VisualizerSchema(BaseModel):
    pandas_code: str = Field(..., description="The Python code generated by the agent to convert data into a Pandas DataFrame to be visualized easily using Matplotlib")
    matplotlib_code: str = Field(..., description="The Python code generated by the agent to visualize data using Matplotlib")

class RouteSchema(BaseModel):
    answer: Literal["ETL", "SQL", "PLOT", "DONE"] = Field(
        ...,
        description=(
        """Which workflow to run NEXT, given the conversation and workflow history so far. 'ETL' extracts/transforms data into Postgres
        tables. 'SQL' answers questions by querying data already in Postgres. 'PLOT' visualizes data already in Postgres and saves an
        image file. Return 'DONE' once enough data or information already exists to fully answer the user's original question and no
        further workflow is needed."""
        ),
    )
    comments: str = Field(..., description="Short rationale for this routing decision.")

class SupervisorSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages to be processed by the Data agent")
    user_question: str = Field(..., description="The original question asked by the user")
    route_response: str = Field(..., description="The response from the router indicating whether to route to SQL or ETL operations, or if the process is complete (DONE).")
    sql_response: str = Field(..., description="The response from the SQL agent after processing the user's question and executing the generated SQL query if it is safe to do so.")
    etl_response: str = Field(..., description="The response from the ETL agent after performing the requested extract/transform/load operations.")
    plot_response: str = Field(..., description="The response/result from the PLOT workflow")